"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oy=!t7aiu-_hpx@=n__aq+mv%sa*6a#5tdl*1uu^w(z=wksn*!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','192.168.0.10','greennuri.info']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'home',
    "django_mysql",
    "apps.dashboard",
    "django_extensions",
    "apps.news",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATIC_URL  = "/static/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ROOT_URLCONF = 'core.urls'

ES_HOST = "192.168.48.3"
ES_PORT = 9200
ES_USER = "elastic"
ES_PASSWORD = "manhae428!"
NEWS_BULK_INDEX = "news_article_bulk"
NEWS_EMBEDDING_INDEX = "news_article_embedding"

DATABASE_ROUTERS = ["core.Router.DemoRouter"]

DATABASE_APPS_MAPPING = {
    "default": "scrap_db",
    "home": "home_db",          
}

DATABASES={
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "dashboard_manager",
        "USER": "scraper",
        "PASSWORD": "Scraper123!",
        "HOST": "192.168.0.143",
        "PORT": "3306",
        "CONN_MAX_AGE": 120,
        "COMMAND_TIMEOUT": 60,
        "engin_options": {"pool_pre_ping": True},
        "OPTIONS": {"charset": "utf8mb4"},
    },
    "news_db": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "news_db",
        "USER": "scraper",
        "PASSWORD": "Scraper123!",
        "HOST": "192.168.0.143",
        "PORT": "3306",
        "CONN_MAX_AGE": 120,
        "COMMAND_TIMEOUT": 60,
        "engin_options": {"pool_pre_ping": True},
        "OPTIONS": {"charset": "utf8mb4"},
    },   
}
 
 